# Generated by Django 5.1.7 on 2025-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=1500)),
                ('zip', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('idproof', models.CharField(max_length=100)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
    ]
