# Generated by Django 5.1.7 on 2025-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_add',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
