# Generated by Django 5.1.7 on 2025-03-21 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_emp_add_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_add',
            name='dept',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
