# Generated by Django 5.1.7 on 2025-03-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_emp_add_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp_add',
        ),
    ]
