# Generated by Django 5.1.7 on 2025-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_empdata_contact_alter_empdata_dept_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empdata',
        ),
    ]
