# Generated by Django 5.1.7 on 2025-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='jdate',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='empdata',
            name='ldate',
            field=models.DateTimeField(max_length=200),
        ),
    ]
