# Generated by Django 5.1.7 on 2025-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_alter_empdata_jdate_alter_empdata_ldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='jdate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='empdata',
            name='ldate',
            field=models.CharField(max_length=200),
        ),
    ]
